apiVersion: v1
kind: Service
metadata:
  name: nats-streaming
  labels:
    component: nats-streaming
spec:
  selector:
    component: nats-streaming
  clusterIP: None
  ports:
  - name: monitor
    port: 8222
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats-streaming
  labels:
    component: nats-streaming
spec:
  serviceName: nats-streaming
  replicas: 3
  selector:
    matchLabels:
      component: nats-streaming
  template:
    metadata:
      labels:
        component: nats-streaming
    spec:
      nodeSelector:
        node-role.kubernetes.io/node: ""
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: component
                  operator: In
                  values:
                    - nats-streaming
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nats-streaming
        image: nats-streaming:0.14.2
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args: [
          "--clustered",
          "--cluster_id", "production",
          "--store", "FILE",
          "--dir", "/data/store",
          "--nats_server", "nats://nats:6222",
          "--http_port", "8222",
          "--cluster_node_id", "$(POD_NAME)",
          "--cluster_peers", "nats-streaming-0,nats-streaming-1,nats-streaming-2",
          "--cluster_log_path", "/data/cluster-log"
        ]
        volumeMounts:
        - mountPath: /data
          name: nats-streaming-data
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 8222
          name: monitor
        readinessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 30
          timeoutSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: nats-streaming-data
    spec:
      storageClassName: rook-ceph-block
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi