apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  repo: https://charts.jetstack.io
  targetNamespace: cert-manager
  version: v0.13.1
  set:
    image.repository: quay.io/jetstack/cert-manager-controller-arm
    webhook.enabled: "false"
    cainjector.image.repository: quay.io/jetstack/cert-manager-cainjector-arm