apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  version: 1.3.1
  targetNamespace: longhorn-system
  valuesContent: |-
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 2
    defaultSettings:
      defaultDataLocality: best-effort
      backupTarget: s3://longhorn-backup@auto/
      backupTargetCredentialSecret: backup-target-credential