apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v13.2.6-20190604
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: false
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "piworker1"
      deviceFilter: "^sd."
    - name: "piworker2"
      deviceFilter: "^sd."
    - name: "piworker3"
      deviceFilter: "^sd."