apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush         1
        Log_Level     error
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   Off
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-loggly.conf
  input-kubernetes.conf: |-
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            container
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  filter-kubernetes.conf: |-
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local
        Tls.verify          Off
        Merge_Log           On
        K8S-Logging.Parser  On
  output-loggly.conf: |-
    [OUTPUT]
        Name             http
        Match            *
        Host             ${LOGGLY_HOSTNAME}
        Port             443
        Tls              On
        Tls.verify       Off
        URI              /bulk/${LOGGLY_TOKEN}/tag/${LOGGLY_TAG}/
        Format           json_lines
        Json_Date_Key    timestamp
        Json_Date_Format iso8601
        Retry_Limit      False
  parsers.conf: |
    [PARSER]
        Name        container
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
      version: v1
      kubernetes.io/cluster-service: "true"
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fluent-bit
        image: hannahsfamily/fluent-bit:1.2.0
        imagePullPolicy: IfNotPresent
        env:
        - name: LOGGLY_HOSTNAME
          value: "logs-01.loggly.com"
        - name: LOGGLY_TAG
          valueFrom:
            secretKeyRef:
              name: fluent-bit
              key: loggly_tag
        - name: LOGGLY_TOKEN
          valueFrom:
            secretKeyRef:
              name: fluent-bit
              key: loggly_token
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule