apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden
spec:
  encryptedData:
    adminToken: AgAuAhZ2B4y++wX75nYBfMNcYNEV7xwGKP6QL1JsP8ihOox9dpgsUpcEyb0YDdGfLpuKo3hoZ8d4bB0uRSmI2lkffgnM1fuV7GZ3aX9c/eGz6mVxlyjJbeRtytMFNFTSa1YRnUFj2g19lASc+iUzRhUT296sxdtYbsWgmNdiOnZIP0rZVN/w6c+9yDayArg9y7tc83g/4tbTvSarv9PKjIcp00WjIqgeGHObHNYrJX+pCL8nwTXhHmeN67+rREh5+AoRVnUOxEUYioocOFFt3Clxv1PdbkT4cdLfjqgP22JIy2v38NnN2akyt2MVQzaSClbIgOC/RTS9RUW+/Qu4tgoA1VUASEopglPrDThnt490HmTk6zCnwZs2HF3lGRNtP1aAywR3zpjPpHvC9ZmyzgUv6QE3f3mJJa5MLj9BIOHKARuBiIzWFMbF1/KAFwrFQ27E6KSnPkD3AW9lPAfBxCfPBKTZ7G0keazw5K4owlGs+s5yoJNEZE0+bkfCcJQBfAYR0141fRQECibQ8cU3zWESu9Fr3VHWJnuBIUdNWbMPbqqPBkvd4b6lAmndjDmuPAT2c7ZQy9iPXy9VseBkR4DcaMkBgZMdxRl8MlYep494Iqd85OSmwc4mF1vwzC5oZWSrKi+QBm90oSgxGPDUdYjHh1AHkgz2OdPcK6hg462vv0VKvlvFoUCIHNWuNVCQ0cdPE6Cilx+EQpUN8GLvcWTHMmubxWtXplEv5V2iMBfUl2s/LzVvehH8PZ+mqeYRqeM/Zb0n0EkBGzwWPDmFbrpG
  template:
    metadata:
      name: vaultwarden