kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
      annotations:
        linkerd.io/inject: enabled
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: cloudflared
          image: msnelling/cloudflared:2021.4.0
          command: ["/usr/local/bin/cloudflared"]
          args: [
            "tunnel",
            "--no-autoupdate",
            "--cred-file", "/secrets/cred.json",
            "--url", "localhost:80",
            "run", "ingress"
          ]
          volumeMounts:
          - name: cf-tunnel-cred
            mountPath: /secrets/cred.json
            subPath: cred.json
          resources:
            limits:
              cpu: 300m
              memory: 40Mi
            requests:
              cpu: 100m
              memory: 20Mi
        - name: traefik
          image: traefik:v2.4.8
          args:
            - --entrypoints.web.Address=:80
            - --providers.kubernetescrd
          resources:
            limits:
              cpu: 500m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - name: web
              containerPort: 80
      volumes:
        - name: cf-tunnel-cred
          secret:
            secretName: cf-tunnel-cred