apiVersion: v1
kind: Service
metadata:
  name: traefik-external
  namespace: kube-system
spec:
  selector:
    app: traefik-external
  type: LoadBalancer
  loadBalancerIP: 10.0.1.50
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: web
    - protocol: TCP
      name: websecure
      port: 443
      targetPort: web
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kube-system
  name: traefik-external
  labels:
    app: traefik-external
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik-external
  template:
    metadata:
      labels:
        app: traefik-external
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.1.6
          args:
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --providers.kubernetescrd
            - --providers.kubernetescrd.ingressclass=traefik-external
          resources:
            limits:
              cpu: 200m
              memory: 35Mi
            requests:
              cpu: 100m
              memory: 20Mi
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080