apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant
data:
  configuration.yaml: |-
    homeassistant:
      name: Home
      elevation: 0
      unit_system: metric
      time_zone: America/Vancouver
    default_config:
    recorder: