apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
  - port: 8123
    targetPort: 8123
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-jiva
  resources:
    requests:
      storage: 500M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      shareProcessNamespace: true
      hostNetwork: true
      containers:
      - name: home-assistant
        image: homeassistant/raspberrypi3-homeassistant:0.109.0
        env:
        - name: TZ
          value: "Asia/Hong_Kong"
        volumeMounts:
        - mountPath: /config
          name: config
        - name: home-assistant-config
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
        ports:
        - containerPort: 8123
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant
        - name: home-assistant-config
          configMap:
            name: home-assistant