apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
  - port: 8123
    targetPort: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: hass-config
  labels:
    app: hass-config
spec:
  selector:
    app: home-assistant
  ports:
  - port: 3218
    targetPort: 3218
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      shareProcessNamespace: true
      hostNetwork: true
      nodeSelector:
        bluetooth: "on"
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: home-assistant
        image: homeassistant/raspberrypi3-homeassistant:0.95.4
        env:
        - name: TZ
          value: "Asia/Hong_Kong"
        volumeMounts:
        - name: storage
          mountPath: /config
        - name: home-assistant-config
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
        ports:
        - containerPort: 8123
      volumes:
        - name: storage
          hostPath:
            path: /var/lib/hass
        - name: home-assistant-config
          configMap:
            name: home-assistant