apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
  - port: 8123
    targetPort: 8123
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  serviceName: home-assistant
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:2021.5.5
        env:
        - name: TZ
          value: "America/Vancouver"
        volumeMounts:
        - name: home-assistant-config
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
        ports:
        - containerPort: 8123
      volumes:
        - name: home-assistant-config
          configMap:
            name: home-assistant