apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: stackgres
  namespace: stackgres
spec:
  repo: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm
  chart: stackgres-operator
  version: 1.3.1
  targetNamespace: stackgres
  valuesContent: |-
    cert:
      certManager:
        autoConfigure: true