---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    kubernetes.io/name: "Metrics-server"
    kubernetes.io/cluster-service: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.1.52
  selector:
    k8s-app: metrics-server
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server-tunnel
  namespace: kube-system
  labels:
    kubernetes.io/name: "Metrics-server-tunnel"
    kubernetes.io/cluster-service: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: metrics-server-tunnel
  namespace: kube-system