apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vault
  namespace: default
spec:
  repo: https://helm.releases.hashicorp.com
  chart: vault
  version: 0.18.0
  targetNamespace: default
  valuesContent: |-
    injector:
      annotations:
        "linkerd.io/inject": "enabled"
        "config.linkerd.io/skip-inbound-ports": "8080"
    ui:
      enabled: true
      activeVaultPodOnly: true
    server:
      updateStrategyType: "RollingUpdate"
      extraArgs: "-config=/secrets/storage.hcl -config=/secrets/seal.hcl"
      tolerations: |
        - key: "SelectedOnly"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector: |
        purpose: dedicated
      annotations:
        "linkerd.io/inject": "enabled"
        "config.linkerd.io/skip-inbound-ports": "8201"
        "config.linkerd.io/skip-outbound-ports": "8201"
      readinessProbe:
        path: /v1/sys/health?standbyok=true
      volumes:
      - name: secrets
        secret:
          secretName: vault
      volumeMounts:
      - name: secrets
        mountPath: /secrets
        readOnly: true
      ha:
        enabled: true
        config: |
          ui = true
          service_registration "kubernetes" {}

          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
