apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: home-assistant
  annotations:
    kubernetes.io/ingress.class: traefik-external
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - home.jimmyau.com
    secretName: jimmyau-com-tls
  rules:
  - host: home.jimmyau.com
    http:
      paths:
      - backend:
          serviceName: home-assistant
          servicePort: 8123