apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  routes:
  - kind: Rule
    match: Host(`home.jimmyau.com`)
    services:
    - name: home-assistant
      port: 8123
  tls:
    secretName: jimmyau-com-tls