apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tides
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  routes:
  - kind: Rule
    match: Host(`tides.jimmyau.com`)
    priority: 1
    services:
    - name: tides-web
      port: 80
  - kind: Rule
    match: Host(`tides.jimmyau.com`) && Method(`POST`)
    priority: 2
    services:
    - name: tides-server
      port: 8080
  tls:
    secretName: jimmyau-com-tls