apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb
spec:
  encryptedData:
    root-password: AgBcZIFg65AUXmuUDMJRjHSBc1I8bcVMtK9RXP0FjkTmoJ1Def2+7iuc23TXz2CLJhHdwiTOSJAGQdc5nd7CnWzAjT9KvRZjD3lJLudtYwZgSiZ/CaUhnnz0BHCQjmzxl4caGddbpHnDs6KLNH2VaGML1zTFa9+jheXrANoaO0lzk/m7+wnqgVXAHeIFgEk02udu8n8JmqYaTkgtV4AG/B4CVcZz6aH4Z8mcbdlRF2KWRRggYNf0hu2PJxRHI2UQed3L0IkhU7Ko2nw9YSWkvUSF/2nwy6wdv3fu9TUt2vZSXlsIILg9nJ2VxwbVidWXWT01+yV5SjxSftSzUMNADc1d5zaqja9DF3VZAjCjSYtLPeoUagCeSe11tg1QTVJ7ubaO9c2WoBeSxuzPTL4Un/Nk1iIsTrIaO2EyH/MLXYGB0E5Wg9GioibwycRkP2BB8U4+bUAl4b+X5yU36pIEyEHny8mGQRd3Hg6Lk+Ajo7D7QXa0iKMGDflz8Q16aWGWVX+FOE2vqkGlyv2zUvgH4cUSIa8Phqx1P4/3iKOquMcivmxXv7ef3MFNLw4SGlkW18ssJfgWipDhVjGW2V35IRiXY7EvMaI+AUbDYDe0sTIPWNTdwkMTvHAoYnhUSkexMvpUNcvsPwLve+3uE2I9Sk/tdhvN9BUBrgjYMu9s89f9BwBF+q9TrVkC9Mv3W4SaMv7X9RZeLKCtpXPzTj3Eg1HA
  template:
    metadata:
      name: mariadb