apiVersion: v1
kind: Service
metadata:
  name: glusterfs-ganesha
  labels:
    component: glusterfs-ganesha
spec:
  selector:
    component: glusterfs-ganesha
  ports:
  - name: nfs
    port: 2049
  type: LoadBalancer
  loadBalancerIP: 10.0.1.52
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glusterfs-ganesha
  labels:
    component: glusterfs-ganesha
spec:
  replicas: 2
  selector:
    matchLabels:
      component: glusterfs-ganesha
  template:
    metadata:
      labels:
        component: glusterfs-ganesha
    spec:
      nodeSelector:
        storagenode: glusterfs
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: component
                  operator: In
                  values:
                    - glusterfs-ganesha
            topologyKey: kubernetes.io/hostname
      containers:
      - name: glusterfs-ganesha
        image: jjbubudi/glusterfs-ganesha:v0.2.0
        env:
        - name: GANESHA_GLUSTER_VOLUME
          value: shared
        - name: GANESHA_GLUSTER_HOSTNAME
          value: glusterfs-0.glusterfs.default.svc.cluster.local
        ports:
        - containerPort: 2049
          name: nfs
        resources:
          limits:
            cpu: 500m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        readinessProbe:
          tcpSocket:
            port: 2049
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 2049
          initialDelaySeconds: 30
          timeoutSeconds: 5